# fly.toml app configuration file generated for ausco on 2025-04-30T12:28:55+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ausco'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
