/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    test: Test;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    test: TestSelect<false> | TestSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    "home-page": HomePage;
    footer: Footer;
    header: Header;
    siteSetting: SiteSetting;
    "about-us-page": AboutUsPage;
    "our-people": OurPerson;
    concerts: Concert;
    "upcoming-concerts": UpcomingConcert;
    "past-concerts": PastConcert;
    "concerts-gallery": ConcertsGallery;
    "annualcamp-gallery": AnnualcampGallery;
    "executivecamp-gallery": ExecutivecampGallery;
    "other-gallery": OtherGallery;
    gallery: Gallery;
    "our-story": OurStory;
  };
  globalsSelect: {
    "home-page": HomePageSelect<false> | HomePageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    siteSetting: SiteSettingSelect<false> | SiteSettingSelect<true>;
    "about-us-page": AboutUsPageSelect<false> | AboutUsPageSelect<true>;
    "our-people": OurPeopleSelect<false> | OurPeopleSelect<true>;
    concerts: ConcertsSelect<false> | ConcertsSelect<true>;
    "upcoming-concerts": UpcomingConcertsSelect<false> | UpcomingConcertsSelect<true>;
    "past-concerts": PastConcertsSelect<false> | PastConcertsSelect<true>;
    "concerts-gallery": ConcertsGallerySelect<false> | ConcertsGallerySelect<true>;
    "annualcamp-gallery": AnnualcampGallerySelect<false> | AnnualcampGallerySelect<true>;
    "executivecamp-gallery": ExecutivecampGallerySelect<false> | ExecutivecampGallerySelect<true>;
    "other-gallery": OtherGallerySelect<false> | OtherGallerySelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    "our-story": OurStorySelect<false> | OurStorySelect<true>;
  };
  locale: null;
  user: User & {
    collection: "users";
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test".
 */
export interface Test {
  id: string;
  title: string;
  description: string;
  dateTime: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: "users";
        value: string | User;
      } | null)
    | ({
        relationTo: "media";
        value: string | Media;
      } | null)
    | ({
        relationTo: "test";
        value: string | Test;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test_select".
 */
export interface TestSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  dateTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero: {
    background: string | Media;
    header: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ("ltr" | "rtl") | null;
        format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    content: string;
  };
  upcomingConcert: {
    title: string;
    poster: string | Media;
    description: string;
    tickets: {
      matinee: {
        date: string;
        location: string;
        ticketUrl: string;
      };
      concert: {
        date: string;
        location: string;
        ticketUrl: string;
      };
    };
  };
  infoCards: {
    aboutUs: {
      image: string | Media;
      description: string;
    };
    ourPeople: {
      image: string | Media;
      description: string;
    };
    contact: {
      image: string | Media;
    };
  };
  featureVideoUrl: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  title: string;
  sections?:
    | {
        title: string;
        options?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  title: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSetting".
 */
export interface SiteSetting {
  id: string;
  primaryLogo: string | Media;
  secondaryLogo: string | Media;
  tertiaryLogo: string | Media;
  links?:
    | {
        platform: "facebook" | "instagram" | "youtube" | "spotify" | "feedbackForm" | "email";
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page".
 */
export interface AboutUsPage {
  id: string;
  hero: {
    description: string;
    stickers?:
      | {
          sticker: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  cards: {
    vision: {
      background: string | Media;
      title: string;
      summary: string;
      description: string;
    };
    story: {
      background: string | Media;
      title: string;
      summary: string;
    };
    constitution: {
      background: string | Media;
      title: string;
      summary: string;
    };
    sponsorsAndPartnerships: {
      background: string | Media;
      title: string;
      summary: string;
      description: string;
      sponsorLogos?:
        | {
            logo: string | Media;
            id?: string | null;
          }[]
        | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-people".
 */
export interface OurPerson {
  id: string;
  image?: (string | null) | Media;
  description?: string | null;
  generalDescription?: string | null;
  execs?:
    | {
        name: string;
        role: string;
        degree: string;
        description: string;
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  playerDescription?: string | null;
  sections?:
    | (
        | {
            sectionTitle: string;
            photo: string | Media;
            players?:
              | {
                  name?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: "large-group";
          }
        | {
            sectionTitle: string;
            photo: string | Media;
            players?:
              | {
                  name?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: "small-group";
          }
      )[]
    | null;
  hallOfFame?:
    | {
        pastPresidents?:
          | {
              name?: string | null;
              description?: string | null;
              image?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        founders?:
          | {
              name?: string | null;
              description?: string | null;
              image?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concerts".
 */
export interface Concert {
  id: string;
  upcoming: string | Media;
  past: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-concerts".
 */
export interface UpcomingConcert {
  id: string;
  hero: string;
  upcomingConcert?: {
    title?: string | null;
    poster?: (string | null) | Media;
    description1?: string | null;
    description2?: string | null;
  };
  semOneEventOne?: {
    title?: string | null;
    date?: string | null;
    location?: string | null;
    ticketUrl?: string | null;
  };
  semOneEventTwo?: {
    title?: string | null;
    date?: string | null;
    location?: string | null;
    ticketUrl?: string | null;
  };
  upcomingConcertTwo?: {
    title?: string | null;
    poster?: (string | null) | Media;
    description1?: string | null;
    description2?: string | null;
  };
  semTwoEventOne?: {
    title?: string | null;
    date?: string | null;
    location?: string | null;
    ticketUrl?: string | null;
  };
  semTwoEventTwo?: {
    title?: string | null;
    date?: string | null;
    location?: string | null;
    ticketUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "past-concerts".
 */
export interface PastConcert {
  id: string;
  headerSection: {
    title: string;
    "short-desc": string;
  };
  years?:
    | {
        year: string;
        concerts: {
          semester1: {
            poster: string | Media;
            semester: string;
            concertTitle: string;
            desc: string;
            videoUrl: string;
            charity: {
              name: string;
              websiteURL: string;
              donationAmount: number;
            };
          };
          semester2: {
            poster: string | Media;
            semester: string;
            concertTitle: string;
            desc: string;
            videoUrl: string;
            charity: {
              name: string;
              websiteURL: string;
              donationAmount: number;
            };
          };
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  concert: string | Media;
  annual: string | Media;
  executive: string | Media;
  other: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
<<<<<<< HEAD
 * via the `definition` "concerts-gallery".
 */
export interface ConcertsGallery {
  id: string;
  title: string;
  albums?:
    | {
        title: string;
        images?:
          | {
              image: string | Media;
              alt?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annualcamp-gallery".
 */
export interface AnnualcampGallery {
  id: string;
  title: string;
  albums?:
    | {
        title: string;
        images?:
          | {
              image: string | Media;
              alt?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "executivecamp-gallery".
 */
export interface ExecutivecampGallery {
  id: string;
  title: string;
  albums?:
    | {
        title: string;
        images?:
          | {
              image: string | Media;
              alt?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-gallery".
 */
export interface OtherGallery {
  id: string;
  title: string;
  albums?:
    | {
        title: string;
        images?:
          | {
              image: string | Media;
              alt?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
=======
 * via the `definition` "our-story".
>>>>>>> origin/main
 */
export interface OurStory {
  id: string;
  OurStoryTitle: string;
  OurStoryDescription: string;
  timeline?:
    | {
        year: string;
        title?: string | null;
        dateInfo?: string | null;
        presidents?:
          | {
              termType: "sem1" | "sem2" | "full" | "co";
              president: string;
              id?: string | null;
            }[]
          | null;
        vicePresidents?:
          | {
              termType: "sem1" | "sem2" | "full" | "co";
              vicePresident: string;
              id?: string | null;
            }[]
          | null;
        conductors?:
          | {
              termType: "sem1" | "sem2" | "full" | "co";
              conductor: string;
              id?: string | null;
            }[]
          | null;
        description: {
          paragraph: string;
          id?: string | null;
        }[];
        image: string | Media;
        meetingMinutes?:
          | {
              meetingRecords: {
                title: string;
                content: string;
                id?: string | null;
              }[];
              establishmentText: string;
              establishmentQuote: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        background?: T;
        header?: T;
        content?: T;
      };
  upcomingConcert?:
    | T
    | {
        title?: T;
        poster?: T;
        description?: T;
        tickets?:
          | T
          | {
              matinee?:
                | T
                | {
                    date?: T;
                    location?: T;
                    ticketUrl?: T;
                  };
              concert?:
                | T
                | {
                    date?: T;
                    location?: T;
                    ticketUrl?: T;
                  };
            };
      };
  infoCards?:
    | T
    | {
        aboutUs?:
          | T
          | {
              image?: T;
              description?: T;
            };
        ourPeople?:
          | T
          | {
              image?: T;
              description?: T;
            };
        contact?:
          | T
          | {
              image?: T;
            };
      };
  featureVideoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  title?: T;
  sections?:
    | T
    | {
        title?: T;
        options?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSetting_select".
 */
export interface SiteSettingSelect<T extends boolean = true> {
  primaryLogo?: T;
  secondaryLogo?: T;
  tertiaryLogo?: T;
  links?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page_select".
 */
export interface AboutUsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        description?: T;
        stickers?:
          | T
          | {
              sticker?: T;
              id?: T;
            };
      };
  cards?:
    | T
    | {
        vision?:
          | T
          | {
              background?: T;
              title?: T;
              summary?: T;
              description?: T;
            };
        story?:
          | T
          | {
              background?: T;
              title?: T;
              summary?: T;
            };
        constitution?:
          | T
          | {
              background?: T;
              title?: T;
              summary?: T;
            };
        sponsorsAndPartnerships?:
          | T
          | {
              background?: T;
              title?: T;
              summary?: T;
              description?: T;
              sponsorLogos?:
                | T
                | {
                    logo?: T;
                    id?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-people_select".
 */
export interface OurPeopleSelect<T extends boolean = true> {
  image?: T;
  description?: T;
  generalDescription?: T;
  execs?:
    | T
    | {
        name?: T;
        role?: T;
        degree?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  playerDescription?: T;
  sections?:
    | T
    | {
        "large-group"?:
          | T
          | {
              sectionTitle?: T;
              photo?: T;
              players?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        "small-group"?:
          | T
          | {
              sectionTitle?: T;
              photo?: T;
              players?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  hallOfFame?:
    | T
    | {
        pastPresidents?:
          | T
          | {
              name?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        founders?:
          | T
          | {
              name?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concerts_select".
 */
export interface ConcertsSelect<T extends boolean = true> {
  upcoming?: T;
  past?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-concerts_select".
 */
export interface UpcomingConcertsSelect<T extends boolean = true> {
  hero?: T;
  upcomingConcert?:
    | T
    | {
        title?: T;
        poster?: T;
        description1?: T;
        description2?: T;
      };
  semOneEventOne?:
    | T
    | {
        title?: T;
        date?: T;
        location?: T;
        ticketUrl?: T;
      };
  semOneEventTwo?:
    | T
    | {
        title?: T;
        date?: T;
        location?: T;
        ticketUrl?: T;
      };
  upcomingConcertTwo?:
    | T
    | {
        title?: T;
        poster?: T;
        description1?: T;
        description2?: T;
      };
  semTwoEventOne?:
    | T
    | {
        title?: T;
        date?: T;
        location?: T;
        ticketUrl?: T;
      };
  semTwoEventTwo?:
    | T
    | {
        title?: T;
        date?: T;
        location?: T;
        ticketUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "past-concerts_select".
 */
export interface PastConcertsSelect<T extends boolean = true> {
  headerSection?:
    | T
    | {
        title?: T;
        "short-desc"?: T;
      };
  years?:
    | T
    | {
        year?: T;
        concerts?:
          | T
          | {
              semester1?:
                | T
                | {
                    poster?: T;
                    semester?: T;
                    concertTitle?: T;
                    desc?: T;
                    videoUrl?: T;
                    charity?:
                      | T
                      | {
                          name?: T;
                          websiteURL?: T;
                          donationAmount?: T;
                        };
                  };
              semester2?:
                | T
                | {
                    poster?: T;
                    semester?: T;
                    concertTitle?: T;
                    desc?: T;
                    videoUrl?: T;
                    charity?:
                      | T
                      | {
                          name?: T;
                          websiteURL?: T;
                          donationAmount?: T;
                        };
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  concert?: T;
  annual?: T;
  executive?: T;
  other?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-story_select".
 */
export interface OurStorySelect<T extends boolean = true> {
  OurStoryTitle?: T;
  OurStoryDescription?: T;
  timeline?:
    | T
    | {
        year?: T;
        title?: T;
        dateInfo?: T;
        presidents?:
          | T
          | {
              termType?: T;
              president?: T;
              id?: T;
            };
        vicePresidents?:
          | T
          | {
              termType?: T;
              vicePresident?: T;
              id?: T;
            };
        conductors?:
          | T
          | {
              termType?: T;
              conductor?: T;
              id?: T;
            };
        description?:
          | T
          | {
              paragraph?: T;
              id?: T;
            };
        image?: T;
        meetingMinutes?:
          | T
          | {
              meetingRecords?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              establishmentText?: T;
              establishmentQuote?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concerts-gallery_select".
 */
export interface ConcertsGallerySelect<T extends boolean = true> {
  title?: T;
  albums?:
    | T
    | {
        title?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annualcamp-gallery_select".
 */
export interface AnnualcampGallerySelect<T extends boolean = true> {
  title?: T;
  albums?:
    | T
    | {
        title?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "executivecamp-gallery_select".
 */
export interface ExecutivecampGallerySelect<T extends boolean = true> {
  title?: T;
  albums?:
    | T
    | {
        title?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-gallery_select".
 */
export interface OtherGallerySelect<T extends boolean = true> {
  title?: T;
  albums?:
    | T
    | {
        title?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
