/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    test: Test;
    Videos: Video;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    test: TestSelect<false> | TestSelect<true>;
    Videos: VideosSelect<false> | VideosSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'landing-page': LandingPage;
    footer: Footer;
    header: Header;
    'about-hero-section': AboutHeroSection;
    'about-first-cards': AboutFirstCard;
    'second-two-card': SecondTwoCard;
    'our-people': OurPerson;
    'concerts-landing': ConcertsLanding;
    'upcoming-concerts': UpcomingConcert;
    'past-concerts': PastConcert;
  };
  globalsSelect: {
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    'about-hero-section': AboutHeroSectionSelect<false> | AboutHeroSectionSelect<true>;
    'about-first-cards': AboutFirstCardsSelect<false> | AboutFirstCardsSelect<true>;
    'second-two-card': SecondTwoCardSelect<false> | SecondTwoCardSelect<true>;
    'our-people': OurPeopleSelect<false> | OurPeopleSelect<true>;
    'concerts-landing': ConcertsLandingSelect<false> | ConcertsLandingSelect<true>;
    'upcoming-concerts': UpcomingConcertsSelect<false> | UpcomingConcertsSelect<true>;
    'past-concerts': PastConcertsSelect<false> | PastConcertsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test".
 */
export interface Test {
  id: string;
  title: string;
  description: string;
  dateTime: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Videos".
 */
export interface Video {
  id: string;
  title: string;
  youtubeUrl: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'test';
        value: string | Test;
      } | null)
    | ({
        relationTo: 'Videos';
        value: string | Video;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test_select".
 */
export interface TestSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  dateTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  youtubeUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: string;
  header: {
    title: string;
    content: string;
  };
  upcomingConcert?: {
    title?: string | null;
    poster?: (string | null) | Media;
    description1?: string | null;
    description2?: string | null;
  };
  matinee?: {
    title?: string | null;
    date?: string | null;
    location?: string | null;
    ticketUrl?: string | null;
  };
  concert?: {
    title?: string | null;
    date?: string | null;
    location?: string | null;
    ticketUrl?: string | null;
  };
  /**
   * Add, edit, or remove cards on the landing page. Each card can have a title, description, image and link.
   */
  infoCards: {
    regularCards: {
      title: string;
      description: string;
      image: string;
      linkText: string;
      linkHref?: string | null;
      id?: string | null;
    }[];
    contactsCard: {
      title: string;
      description: string;
      image: string;
      linkText: string;
      linkHref?: string | null;
      contacts: {
        text: string;
        href?: string | null;
        icon: 'mail' | 'instagram' | 'facebook';
        id?: string | null;
      }[];
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo: string | Media;
  title: string;
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'spotify';
        url: string;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo?: (string | null) | Media;
  title?: string | null;
  navLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-hero-section".
 */
export interface AboutHeroSection {
  id: string;
  aboutUsStickers?:
    | {
        'sticker-image': string | Media;
        id?: string | null;
      }[]
    | null;
  AboutUsHeader?: string | null;
  AboutUsDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-first-cards".
 */
export interface AboutFirstCard {
  id: string;
  visionCard: {
    'background-image': string | Media;
    title: string;
    'short-desc': string;
    'full-desc': string;
  };
  historyCard: {
    'background-image': string | Media;
    title: string;
    'short-desc': string;
    'full-desc': string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "second-two-card".
 */
export interface SecondTwoCard {
  id: string;
  leftBox: {
    title: string;
    shortDescription: string;
    fullText: string;
    backgroundImage?: (string | null) | Media;
  };
  rightBox: {
    title: string;
    shortDescription: string;
    fullText: string;
    sponsorLogos?:
      | {
          logo: string | Media;
          id?: string | null;
        }[]
      | null;
    backgroundImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-people".
 */
export interface OurPerson {
  id: string;
  generalDescription?: string | null;
  execs?:
    | {
        name: string;
        role: string;
        degree: string;
        description: string;
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  playerDescription?: string | null;
  sections?:
    | (
        | {
            sectionTitle: string;
            photo: string | Media;
            players?:
              | {
                  name?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'large-group';
          }
        | {
            sectionTitle: string;
            photo: string | Media;
            players?:
              | {
                  name?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'small-group';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concerts-landing".
 */
export interface ConcertsLanding {
  id: string;
  upcomingCard: {
    'background-image': string | Media;
  };
  pastCard: {
    'background-image': string | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-concerts".
 */
export interface UpcomingConcert {
  id: string;
  hero: string;
  upcomingConcert?: {
    title?: string | null;
    poster?: (string | null) | Media;
    description1?: string | null;
    description2?: string | null;
  };
  eventOne?: {
    title?: string | null;
    date?: string | null;
    location?: string | null;
    ticketUrl?: string | null;
  };
  eventTwo?: {
    title?: string | null;
    date?: string | null;
    location?: string | null;
    ticketUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "past-concerts".
 */
export interface PastConcert {
  id: string;
  headerSection: {
    title: string;
    'short-desc': string;
  };
  years?:
    | {
        year: string;
        concerts: {
          semester1: {
            poster: string | Media;
            semester: string;
            concertTitle: string;
            desc: string;
            videoUrl: string;
            charity: {
              name: string;
              websiteURL: string;
              donationAmount: number;
            };
          };
          semester2: {
            poster: string | Media;
            semester: string;
            concertTitle: string;
            desc: string;
            videoUrl: string;
            charity: {
              name: string;
              websiteURL: string;
              donationAmount: number;
            };
          };
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        title?: T;
        content?: T;
      };
  upcomingConcert?:
    | T
    | {
        title?: T;
        poster?: T;
        description1?: T;
        description2?: T;
      };
  matinee?:
    | T
    | {
        title?: T;
        date?: T;
        location?: T;
        ticketUrl?: T;
      };
  concert?:
    | T
    | {
        title?: T;
        date?: T;
        location?: T;
        ticketUrl?: T;
      };
  infoCards?:
    | T
    | {
        regularCards?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              linkText?: T;
              linkHref?: T;
              id?: T;
            };
        contactsCard?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              linkText?: T;
              linkHref?: T;
              contacts?:
                | T
                | {
                    text?: T;
                    href?: T;
                    icon?: T;
                    id?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  title?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  title?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-hero-section_select".
 */
export interface AboutHeroSectionSelect<T extends boolean = true> {
  aboutUsStickers?:
    | T
    | {
        'sticker-image'?: T;
        id?: T;
      };
  AboutUsHeader?: T;
  AboutUsDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-first-cards_select".
 */
export interface AboutFirstCardsSelect<T extends boolean = true> {
  visionCard?:
    | T
    | {
        'background-image'?: T;
        title?: T;
        'short-desc'?: T;
        'full-desc'?: T;
      };
  historyCard?:
    | T
    | {
        'background-image'?: T;
        title?: T;
        'short-desc'?: T;
        'full-desc'?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "second-two-card_select".
 */
export interface SecondTwoCardSelect<T extends boolean = true> {
  leftBox?:
    | T
    | {
        title?: T;
        shortDescription?: T;
        fullText?: T;
        backgroundImage?: T;
      };
  rightBox?:
    | T
    | {
        title?: T;
        shortDescription?: T;
        fullText?: T;
        sponsorLogos?:
          | T
          | {
              logo?: T;
              id?: T;
            };
        backgroundImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-people_select".
 */
export interface OurPeopleSelect<T extends boolean = true> {
  generalDescription?: T;
  execs?:
    | T
    | {
        name?: T;
        role?: T;
        degree?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  playerDescription?: T;
  sections?:
    | T
    | {
        'large-group'?:
          | T
          | {
              sectionTitle?: T;
              photo?: T;
              players?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'small-group'?:
          | T
          | {
              sectionTitle?: T;
              photo?: T;
              players?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concerts-landing_select".
 */
export interface ConcertsLandingSelect<T extends boolean = true> {
  upcomingCard?:
    | T
    | {
        'background-image'?: T;
      };
  pastCard?:
    | T
    | {
        'background-image'?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-concerts_select".
 */
export interface UpcomingConcertsSelect<T extends boolean = true> {
  hero?: T;
  upcomingConcert?:
    | T
    | {
        title?: T;
        poster?: T;
        description1?: T;
        description2?: T;
      };
  eventOne?:
    | T
    | {
        title?: T;
        date?: T;
        location?: T;
        ticketUrl?: T;
      };
  eventTwo?:
    | T
    | {
        title?: T;
        date?: T;
        location?: T;
        ticketUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "past-concerts_select".
 */
export interface PastConcertsSelect<T extends boolean = true> {
  headerSection?:
    | T
    | {
        title?: T;
        'short-desc'?: T;
      };
  years?:
    | T
    | {
        year?: T;
        concerts?:
          | T
          | {
              semester1?:
                | T
                | {
                    poster?: T;
                    semester?: T;
                    concertTitle?: T;
                    desc?: T;
                    videoUrl?: T;
                    charity?:
                      | T
                      | {
                          name?: T;
                          websiteURL?: T;
                          donationAmount?: T;
                        };
                  };
              semester2?:
                | T
                | {
                    poster?: T;
                    semester?: T;
                    concertTitle?: T;
                    desc?: T;
                    videoUrl?: T;
                    charity?:
                      | T
                      | {
                          name?: T;
                          websiteURL?: T;
                          donationAmount?: T;
                        };
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}