# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --remote-only --config fly.toml \
            --build-secret DATABASE_URI=${{ secrets.DATABASE_URI }} \
            --build-secret PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }} \

        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
